### ISSUE TITLE
Hash2phone reports ImportError: No module named psycopg2

### ISSUE THREAD

**Issue by jhuettner** [hexway/apple_bleee#11]
On Mint 19.1, even after pip install psycopg2, hash2phone reports ImportError: No module named psycopg2.  Solution was to apt install python-psycopg2.

**Comment by zsnell02** [comment]
Please mark as closed. Also, you could do sudo pip install psycopg2-binary. As well as this, make sure your default python is python3, otherwise you would have to do pip3.
