### ISSUE TITLE
Zeroes in Phone hash but not in AppleID hash

### ISSUE THREAD

**Issue by zhovner** [hexway/apple_bleee#15]
Sometimes I get strange hashes values. Empty Phone hash and Email hash, but correct AppleID hash. The same phone sometimes returns correct phone hash.

![image](https://user-images.githubusercontent.com/774290/62643718-43a6b880-b951-11e9-82a2-7970d517965a.png)

I also get this error sometimes while `ble_read_state.py` running:

```
Exception when calling handler with a BLE advertising event: ValueError("invalid literal for int() with base 16: ''")
```

Kali linux 2019.3
Bluetooth usb dongle CSR8510

**Comment by hexway** [comment]
We also sometimes get zero hashes and still have not understood why this is happening. As if the phone number is not associated with AppleID. We identified 3 actions that fix this device behavior:
1) reboot
2) rearrangement of sim cards and reactivation and iMessage
3) on/off iMessage

**Comment by zhovner** [comment]
I get the correct hash from the same device after few minutes without changing any settings on the phone.

BTW, sometimes I see empty hashes at all, but green `X` indicates that something was sniffed.
![image](https://user-images.githubusercontent.com/774290/62651900-b53b3280-b962-11e9-8c22-837af4844446.png)

It would be nice to enable some debug mode to look closer at this issues. I'm not familiar with bluez yet, but I will try debug it.

**Comment by zhovner** [comment]
I found that in some cases phone hash can be from email if iMessage account doest not have a phone number and attached only to email.
