### ISSUE TITLE
No traffic in ble_read_state

### ISSUE THREAD

**Issue by ajloveless** [hexway/apple_bleee#24]
I have owl and ble_read_state.py running side by side, a lot of traffic is coming through in owl, yet nothing is showing up in apple devices scanner (as shown in attachment). Is everything set up right?  Here's the configuration of awdl0 pulled from ip addr (mac addresses have been removed): 

`12: awdl0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet6 fe80::xxxx:xxxx:xxxx:xxxx/64 scope link 
       valid_lft forever preferred_lft forever
`
![appleblee](https://user-images.githubusercontent.com/22356592/65528931-4a6a9a00-dec3-11e9-9a0a-15c2824736b7.png)

**Comment by Arviddk** [comment]
I have this issue too. Any fix?

**Comment by ajloveless** [comment]
A fix I have found is to run ble.recon in bettercap, then start ble_read_state..
