### ISSUE TITLE
ModuleNotFoundError: No module named 'bluetooth._bluetooth'

### ISSUE THREAD

**Issue by aimzieslol** [hexway/apple_bleee#3]
Getting this when I run:

```
python ble_read_state.py
```

Weirdly, in the `PyBluez` package it's got the same `_bluetooth` import-- and it can't find it either. I cloned the `PyBluez` project from GitHub and have searched all of the source code and it's just not there.

I'm using Python 3.7 on MacOS (Mojave, I believe). I know it's experimental but perhaps there's an alternative package I can use/install?

**Comment by foxt** [comment]
Use Linux. Bluez is not supported under macOS as far as I know

**Comment by hexway** [comment]
We didn't test these scripts on Mac. Please use VM
