### ISSUE TITLE
Incorrect comparing

### ISSUE THREAD

**Issue by ijevius** [hexway/apple_bleee#7]
An error in 37 line while comparing two values. You should use ==, not `is`. Else it isn't sure correct comparing result.

https://github.com/hexway/apple_bleee/blob/4b0224ff0bb032390b86ef16c770b2342896088d/hash2phone/hashmap_gen.py#L37

**Comment by xuiqzy** [comment]
fixed with commit d9ecb3bece9844e7f5b56d24a8833c41164500d8
can be closed by maintainer or @ijevius if no further issue with it
